# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "DynVarMIP: The Dynamics and Variability Model Intercomparison Project"
license = "MIT"
licenselink = "https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "The web home of the DynVarMIP project withint the CMIP6."
homepage = "https://DynVarMIP.github.io"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "Ed Gerber"
  homepage = "https://www.edwinpgerber.github.com/"
